eventsApps.controller("EventController", function ($scope) {
    $scope.boolValue = true;
   
    


    $scope.event = {
        name: "Angular Boot Camp",
        date: "1/1/2015",
        time: "10:30",
        location: {
            address: "Messinias 21",
            city: "Athens",
            province: "ca"
        },
        imageUrl: "img/AngularJS_logo.png",
        sessions: [
            {
                name: "directives masterclass",
                CodePage: "Specifies the character set that will be used when displaying dynamic content",
                LCID: "Sets or returns an integer that specifies a location or region.Contents like date,time,and currency will be displayed according to that                                location or region",
                Duration: 1,
                SessionID: "Returns a unique id for each user.The unique id is generated by the server",
                Timeout: "Sets or returns the timeout period( in minutes) for the Session object in this application",
                upVoteCount: 1
            },
            {
                name: "scopes for fun and profit",
                CodePage: "Specifies the character set that will be used when displaying dynamic content",
                LCID: "Sets or returns an integer that specifies a location or region.Contents like date,time,and currency will be displayed according to that                                location or region",
                Duration: 2,
                SessionID: "Returns a unique id for each user.The unique id is generated by the server",
                Timeout: "Sets or returns the timeout period( in minutes) for the Session object in this application",
                upVoteCount: 1
            },
            {
                name: "well behaved controllers",
                CodePage: "Specifies the character set that will be used when displaying dynamic content",
                LCID: "Sets or returns an integer that specifies a location or region.Contents like date,time,and currency will be displayed according to that                                location or region",
                Duration: 3,
                SessionID: "Returns a unique id for each user.The unique id is generated by the server",
                Timeout: "Sets or returns the timeout period( in minutes) for the Session object in this application",
                upVoteCount: 2
            },
            {
                name: "asdf behaved sdsdsd",
                CodePage: "Specifies the character set that will be used when displaying dynamic content",
                LCID: "Sets or returns an integer that specifies a location or region.Contents like date,time,and currency will be displayed according to that                                location or region",
                Duration: 4,
                SessionID: "Returns a unique id for each user.The unique id is generated by the server",
                Timeout: "Sets or returns the timeout period( in minutes) for the Session object in this application",
                upVoteCount: 2
            }
            

        ]

    }
    $scope.upVoteSession = function (cat) {
        cat.upVoteCount++;

    };
    $scope.downVoteSession = function (cat) {
        cat.upVoteCount--;

    };


});
